### ISSUE TITLE
Pagination doesn't work on Client > Authorization tab

### ISSUE THREAD

**Issue by flipp5b** [keycloak/keycloak-ui#2382]
### Describe the bug

If we have more than 10 resources, only the first 10 are shown. The same is true for the other sub-tabs. Navigation arrows are disabled, and a page size chooser doesn't work as well: there is no reaction when we switch to "20 per page" or any other value.

### Version

17.0.1

**Comment by ssilvert** [comment]
@flipp5b What kind of resources are you talking about?  What tab and section are you working with?

**Comment by flipp5b** [comment]
@ssilvert I mean resources which we can manage under "Authorization" tab in client editor.

Here's how it looks in my case (although there are more than 10 resources, navigation arrows are disabled, and a page size chooser doesn't work):

![Screenshot from 2022-04-06 14-10-45](https://user-images.githubusercontent.com/5507566/161963345-76481611-fc99-44dc-b3f1-a5d86a68c2ae.png)

For me, the same is true for other sub-tabs under the "Authorization" tab.

**Comment by ssilvert** [comment]
Got it.  Thanks.  We will get this fixed in the next release.

**Comment by Duskstrider** [comment]
Is this really fixed?

We can still reproduce the bug in keycloak 20.0.1.

Adding a screenshot from a Chrome Browser in the Windows 11 OS as a "proof":

![Image8](https://user-images.githubusercontent.com/69248833/217183351-8b948b48-57f4-4fbd-9f02-bde1a120fa77.png)

Best wishes to everyone and thanks for all your great work,
Martin

**Comment by edewit** [comment]
fixed with #4349
