### ISSUE TITLE
Assign roles to account - filter doesn't work

### ISSUE THREAD

**Issue by mbikl** [keycloak/keycloak-ui#3736]
### Describe the bug

I use Assign roles to accont, and I want to filter a list of roles. The filter doesn't work. I get all roles.

Thank you

Martin Bíkl

![image](https://user-images.githubusercontent.com/15977094/200793052-a20c8bcc-356a-49df-8a60-f97dd22c591f.png)

### Version

20.0.0

### Environment

Edge - last version

### Expected behavior

Filter will work

**Comment by edewit** [comment]
fixed by https://github.com/keycloak/keycloak-ui/pull/3775

**Comment by Davidgiordano74** [comment]
Hello,
This issue is marked as fixed but I still have the issue in Keycloak 20.0.2. Are you aware of this issue ?
Thanks you.

**Comment by edewit** [comment]
it will be fixed in the next release, 20.0.2 only had a limited number of issues
